on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout reusable workflow dir
      uses: actions/checkout@v3
      with:
        repository: dipuerto/scripting_test
        token: ${{ secrets.ACTION_TOKEN }}
        #path: reusable-workflow-repo
    - name: Ejecutar script desde el repositorio clonado
      run: |
        bash my_script.sh "Hola bb"
